version: "3.4"
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "443:80"

    mongo:
        image: mongo
        ports:
          - "27017:27017"
        volumes:
          - mongodb:/data/db  
volumes:
  mongodb: